using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Hazard : MonoBehaviour
{
    public GameObject playerDeathPrefab;
    public AudioClip deathClip;
    public Sprite hitSprite;
    private SpriteRenderer spriteRenderer;


     void Awake()
    {
        spriteRenderer = GetComponent<SpriteRenderer>();
    }


     void OnCollisionEnter2D(Collision2D coll)
    {
        if(coll.transform.tag=="Player")
        {
            var audioSource = GetComponent<AudioSource>();
            if(audioSource != null && deathClip !=null)
            {
                audioSource.PlayOneShot(deathClip);
            }

            Instantiate(playerDeathPrefab, coll.contacts[0].point, Quaternion.identity);
            spriteRenderer.sprite = hitSprite;

            Destroy(coll.gameObject);
        }
    }


    void Start()
    {
        
    }

    
    void Update()
    {
        
    }
}
